language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN= "c5dd5ee0-28ab-406d-bc1b-2aee16ebb865"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - vasilenko.lesnik2017@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always